import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import SmoothScrolling from "@/components/smoothScroll";
import GrainBackground from "@/components/grain";



const myFont = localFont({ src: '../public/fonts/GeneralSans-Medium.woff2' })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <GrainBackground/>

        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
